apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: one-gate-payment
  labels:
    app: payment-service
type: Opaque
stringData:
  db-username: "developer"
  db-password: "developer123"
  gopay-base-url: "https://gopay-service-external-services.apps.ocp-one-gate-payment.skynux.fun/gopay"
  gopay-client-id: "gopay_client_123"
  gopay-client-secret: "gopay_client_secret_123"
  gopay-signature: "gopay_signature_123"
  shopee-pay-base-url: "https://shopee-pay-service-external-services.apps.ocp-one-gate-payment.skynux.fun/v2/shopeepay"
  shopee-pay-merchant-id: "SHOPEE_MERCHANT_001"
  shopee-pay-api-key: "ShopeePayApiKey123"
  shopee-pay-signature: "ShopeePaySignature456"
  bootstrap-servers: "one-gate-payment-kafka-kafka-bootstrap:9092"
  redis-password: "developer123"